# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

#
# Install library specific stuff
#

COMPILE_OBJ=main.obj applic.obj menus.obj data.obj drvcount.obj install.obj &
            files.obj reboot.obj fatinst.obj fscreate.obj Ugp130a4.obj
            

LIB_NAME=install.lib
LIST_FILE=install.lst
LIB_OBJ=-+main.obj -+applic.obj -+menus.obj -+data.obj -+drvcount.obj -+install.obj &
        -+files.obj -+reboot.obj -+fatinst.obj -+fscreate.obj -+Ugp130a4.obj

#
# Generic library stuff
#

!include ..\MakeCommon.mak
