# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

#main makefile for split

EXE_FILE=split
MAP_FILE=split.map

OBJ=starter.obj split.obj io.obj
FIL_OBJ=starter.obj, split.obj, io.obj

INCPATH=.

C_OPTIONS=-w4 -e25 -ei -zp1 -zq -zls -od -s -d2 -3 -bt=dos -fo=.obj -ms -i$(INCPATH)
ASM_OPTIONS=-zq
LINK_OPTIONS=FORMAT dos op m op nod op maxe=25 op d op q op symf

C=wcc $(C_OPTIONS)
ASM=wasm $(ASM_OPTIONS)
LINK=wlink

$(EXE_FILE): .SYMBOLIC $(OBJ)
    $(LINK) name $(EXE_FILE) $(LINK_OPTIONS) FIL $(FIL_OBJ)

clean: .SYMBOLIC
    @if exist *.obj del *.obj
    @if exist *.bak del *.bak
    @if exist *.exe del *.exe
    @if exist *.map del *.map

.c.obj:
    $(C) $<

.asm.obj:
    $(ASM) $<

