# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

#
# Graph library specific stuff
#

COMPILE_OBJ=graph.obj palette.obj vpgraph.obj cursor.obj pmraw.obj &
            pmgraph.obj rmgraph.obj pmlib.obj dcx.obj int10.obj &
			retrace.obj rgb.obj
LIB_NAME=graph.lib
LIST_FILE=graph.lst
LIB_OBJ=-+graph.obj -+palette.obj -+vpgraph.obj -+cursor.obj -+pmraw.obj &
        -+pmgraph.obj -+rmgraph.obj -+pmlib.obj -+dcx.obj -+int10.obj &
		-+retrace.obj -+rgb.obj

#
# Generic library stuff
#

!include ..\MakeCommon.mak
