# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
# Copyright (c) 2018 by Norman Back:

#main makefile for xoslload.xcf

LIBPATH=xoslload;mmu;io;string;text;misc;freemem
LIB_FILES=xoslload.lib,mmu.lib,io.lib,string.lib,text.lib,misc.lib,freemem.lib
          

!ifdef DOS_DEBUG
MAKE_OPTIONS=-DDOS_DEBUG=1
!endif

OBJ_FILES=misc\starter.obj,
LNK_FILE=xoslload.exe
MAP_FILE=xoslload.map

!ifdef DOS_DEBUG
MAKE_OPTIONS=DOS_DEBUG=1
LINK_OPTIONS=d all SYS dos op m op nod libp $(LIBPATH) libf $(OBJ_FILES) $(LIB_FILES) op maxe=25 op d op q op symf
#LINK_OPTIONS=FORMAT dos com op m op nod libp $(LIBPATH) libf $(OBJ_FILES) $(LIB_FILES) op maxe=25 op d op q op symf
!else
LINK_OPTIONS=d all SYS dos op m op nod libp $(LIBPATH) libf $(OBJ_FILES) $(LIB_FILES) op maxe=25 op d op q op symf
#LINK_OPTIONS=FORMAT dos com op m op nod libp $(LIBPATH) libf $(OBJ_FILES) $(LIB_FILES) op maxe=25 op d op q op symf
!endif

LINK=wlink
MAKE=wmake $(MAKE_OPTIONS)

ENTER=cd
LEAVE=$(ENTER) ..
DELETE=del

all: xoslload mmu io string text misc .SYMBOLIC
   $(LINK) name $(LNK_FILE) $(LINK_OPTIONS)
   exe2bin -h -r -l=0x6000 $(LNK_FILE)
   copy	xoslload.bin xoslload.com
   copy xoslload.com xoslload.xcf


link: .SYMBOLIC
   $(LINK) name $(OBJ_FILES) $(LNK_FILE) $(LINK_OPTIONS)

xoslload: .SYMBOLIC
   $(ENTER) xoslload
   $(MAKE)
   $(LEAVE)

mmu: .SYMBOLIC
   $(ENTER) mmu
   $(MAKE)
   $(LEAVE)

io: .SYMBOLIC
   $(ENTER) io
   $(MAKE)
   $(LEAVE)

string: .SYMBOLIC
   $(ENTER) string
   $(MAKE)
   $(LEAVE)

text: .SYMBOLIC
   $(ENTER) text
   $(MAKE)
   $(LEAVE)

misc: .SYMBOLIC
   $(ENTER) misc
   $(MAKE)
   $(LEAVE)

clean: .SYMBOLIC
   $(ENTER) xoslload
   wmake clean
   $(ENTER) ..\mmu
   wmake clean
   $(ENTER) ..\io
   wmake clean
   $(ENTER) ..\string
   wmake clean
   $(ENTER) ..\text
   wmake clean
   $(ENTER) ..\misc
   wmake clean
   $(LEAVE)
   @del xoslload.xcf
   @del xoslload.map
