# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

#
# Text library specific stuff
#

COMPILE_OBJ=text.obj
LIB_NAME=text.lib
LIST_FILE=text.lst
LIB_OBJ=-+text.obj

#
# Generic library stuff
#

!include ..\MakeCommon.mak
