# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

#
# XOSLLoad library specific stuff
#

COMPILE_OBJ=main.obj execute.obj bypass.obj ptab.obj encpwd.obj
LIB_NAME=xoslload.lib
LIST_FILE=xoslload.lst
LIB_OBJ=-+main.obj -+execute.obj -+bypass.obj -+ptab.obj -+encpwd.obj

#
# Generic library stuff
#
!include ..\MakeCommon.mak
