# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

#
# Mouse library specific stuff
#

COMPILE_OBJ=mouse.obj ps2.obj com.obj
LIB_NAME=mouse.lib
LIST_FILE=mouse.lst
LIB_OBJ=-+mouse.obj -+ps2.obj -+com.obj

#
# Generic library stuff
#

!include ..\MakeCommon.mak
