# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

#main makefile for XOSL

LIBPATH=mmu;timer;text;string;xosl;mouse;misc;graph;keyboard;gui;quit;io;debug;freemem
LIB_FILES=xosl.lib,mmu.lib,timer.lib,text.lib,string.lib,mouse.lib,misc.lib,&
          graph.lib,keyboard.lib,gui.lib,io.lib,quit.lib,debug.lib,freemem.lib

OBJ_FILES=misc\starter.obj,misc\a20line.obj,misc\a20stat.obj,
EXE_FILE=xosl
MAP_FILE=xosl.map
#EXE_FILE=xosl.exe

!ifdef DOS_DEBUG
MAKE_OPTIONS=DOS_DEBUG=1
LINK_OPTIONS=d all SYS dos op m op nod libp $(LIBPATH) libf $(OBJ_FILES) $(LIB_FILES) op maxe=25 op d op q op symf
!else
LINK_OPTIONS=d all SYS dos op m op nod libp $(LIBPATH) libf $(OBJ_FILES) $(LIB_FILES) op maxe=25 op d op q op symf
!endif

LINK=wlink
MAKE=wmake $(MAKE_OPTIONS)

#ENTER=@cd
ENTER=cd
LEAVE=$(ENTER) ..

all: xosl gui graph text mmu string io mouse misc keyboard timer quit debug freemem .SYMBOLIC
   $(LINK) name $(EXE_FILE) $(LINK_OPTIONS)

link: .SYMBOLIC
   $(LINK) name $(EXE_FILE) $(LINK_OPTIONS)

xosl: .SYMBOLIC
   $(ENTER) xosl
   $(MAKE)
   $(LEAVE)

misc: .SYMBOLIC
   $(ENTER) misc
   $(MAKE)
   $(LEAVE)

gui: .SYMBOLIC
   $(ENTER) gui
   $(MAKE)
   $(LEAVE)

graph: .SYMBOLIC
   $(ENTER) graph
   $(MAKE)
   $(LEAVE)

text: .SYMBOLIC
   $(ENTER) text
   $(MAKE)
   $(LEAVE)

mmu: .SYMBOLIC
   $(ENTER) mmu
   $(MAKE)
   $(LEAVE)

string: .SYMBOLIC
   $(ENTER) string
   $(MAKE)
   $(LEAVE)

io: .SYMBOLIC
   $(ENTER) io
   $(MAKE)
   $(LEAVE)

mouse: .SYMBOLIC
   $(ENTER) mouse
   $(MAKE)
   $(LEAVE)

keyboard: .SYMBOLIC
   $(ENTER) keyboard
   $(MAKE)
   $(LEAVE)

timer: .SYMBOLIC
   $(ENTER) timer
   $(MAKE)
   $(LEAVE)

quit: .SYMBOLIC
   $(ENTER) quit
   $(MAKE)
   $(LEAVE)

debug: .SYMBOLIC
   $(ENTER) debug
   $(MAKE)
   $(LEAVE)

freemem: .SYMBOLIC
   $(ENTER) freemem
   $(MAKE)
   $(LEAVE)

clean: .SYMBOLIC
   $(ENTER) xosl
   wmake clean
   $(ENTER) ..\misc
   wmake clean
   $(ENTER) ..\gui
   wmake clean
   $(ENTER) ..\graph
   wmake clean
   $(ENTER) ..\text
   wmake clean
   $(ENTER) ..\mmu
   wmake clean
   $(ENTER) ..\string
   wmake clean
   $(ENTER) ..\io
   wmake clean
   $(ENTER) ..\mouse
   wmake clean
   $(ENTER) ..\keyboard
   wmake clean
   $(ENTER) ..\timer
   wmake clean
   $(ENTER) ..\quit
   wmake clean
   $(ENTER) ..\debug
   wmake clean
   $(ENTER) ..\include
   @if exist *.bak del *.bak
   $(LEAVE)
   @if exist xosl.exe del xosl.exe
   @if exist xosl.map del xosl.map
   @if exist xosl.sym del xosl.sym
   @if exist *.XXF del *.XXF
	 
