# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

#
# User Interface library specific stuff
#

COMPILE_OBJ=textscr.obj textui.obj textlist.obj textwnd.obj &
            textbox.obj textpop.obj
LIB_NAME=ui.lib
LIST_FILE=ui.lst
LIB_OBJ=-+textscr.obj -+textui.obj -+textlist.obj -+textwnd.obj &
        -+textbox.obj -+textpop.obj

#
# Generic library stuff
#

!include ..\MakeCommon.mak
