# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

#
# Quit + Advanced Power Management library specific stuff
#

COMPILE_OBJ=quit.obj apm.obj apmif.obj reboot.obj
LIB_NAME=quit.lib
LIST_FILE=quit.lst
LIB_OBJ=-+quit.obj -+apm.obj -+apmif.obj -+reboot.obj

#
# Generic library stuff
#

!include ..\MakeCommon.mak
