# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

#main makefile for INSTALL.EXE

LIBPATH=install;io;mouse;vesa;ui;keyboard;text;string
LIB_FILES=install.lib,io.lib,mouse.lib,string.lib,&
          vesa.lib,ui.lib,keyboard.lib,text.lib

OBJ_FILES=
LNK_FILE=install.exe
MAP_FILE=install.map

!ifdef DOS_DEBUG
MAKE_OPTIONS=DOS_DEBUG=1
#LINK_OPTIONS=d all SYS dos op m op maxe=25 op q op symf libp $(LIBPATH) libf $(OBJ_FILES) $(LIB_FILES)
LINK_OPTIONS=debug dwarf SYS dos op m op maxe=25 op q op symf op stack=8192 libp $(LIBPATH) libf $(OBJ_FILES) $(LIB_FILES)
!else
#LINK_OPTIONS=d all SYS dos op m op maxe=25 op q op symf libp $(LIBPATH) libf $(OBJ_FILES) $(LIB_FILES)
LINK_OPTIONS=debug dwarf SYS dos op m op maxe=25 op symf op stack=8192 libp $(LIBPATH) libf $(OBJ_FILES) $(LIB_FILES)
!endif

!ifdef DISABLE_LBA
MAKE_OPTIONS=DISABLE_LBA=1 $(MAKE_OPTIONS)
!endif

LINK=wlink
MAKE=wmake $(MAKE_OPTIONS)

#ENTER=@cd
ENTER=cd
LEAVE=$(ENTER) ..

all: $(LNK_FILE)

$(LNK_FILE): install io mouse vesa ui keyboard text string .SYMBOLIC
   $(LINK) name $(LNK_FILE) $(LINK_OPTIONS)

link: .SYMBOLIC
   $(LINK) name $(LNK_FILE) $(LINK_OPTIONS)

install: .SYMBOLIC
   $(ENTER) install
   $(MAKE)
   $(LEAVE)

mmu: .SYMBOLIC
   $(ENTER) mmu
   $(MAKE)
   $(LEAVE)

io: .SYMBOLIC
   $(ENTER) io
   $(MAKE)
   $(LEAVE)

mouse: .SYMBOLIC
   $(ENTER) mouse
   $(MAKE)
   $(LEAVE)

string: .SYMBOLIC
   $(ENTER) string
   $(MAKE)
   $(LEAVE)

vesa: .SYMBOLIC
   $(ENTER) vesa
   $(MAKE)
   $(LEAVE)

misc: .SYMBOLIC
   $(ENTER) misc
   $(MAKE)
   $(LEAVE)

ui: .SYMBOLIC
   $(ENTER) ui
   $(MAKE)
   $(LEAVE)

keyboard: .SYMBOLIC
   $(ENTER) keyboard
   $(MAKE)
   $(LEAVE)

text: .SYMBOLIC
   $(ENTER) text
   $(MAKE)
   $(LEAVE)


clean: .SYMBOLIC
   $(ENTER) install
   wmake clean
   #$(ENTER) ..\mmu
   #wmake clean
   $(ENTER) ..\io
   wmake clean
   $(ENTER) ..\mouse
   wmake clean
   $(ENTER) ..\string
   wmake clean
   $(ENTER) ..\vesa
   wmake clean
   #$(ENTER) ..\misc
   #wmake clean
   $(ENTER) ..\ui
   wmake clean
   $(ENTER) ..\keyboard
   wmake clean
   $(ENTER) ..\text
   wmake clean
   $(ENTER) ..\include
   @if exist *.bak del *.bak
   $(LEAVE)
   @if exist install.exe del install.exe
   @if exist install.map del install.map
   @if exist install.sym del install.sym
   @if exist *.bak del *.bak
