# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

#
# misc library specific stuff
#

# NOTE: MAKEFILE doesn't put starter.obj in misc.lib!

COMPILE_OBJ=starter.obj a20line.obj a20stat.obj int.obj weird.obj ctype.obj wcpp4stuff.obj
LIB_NAME=misc.lib
LIST_FILE=misc.lst
#LIB_OBJ=-+int.obj -+weird.obj -+ctype.obj -+wcpp4stuff.obj -+i4d.obj -+i4m.obj
LIB_OBJ=-+a20line.obj -+a20stat.obj -+int.obj -+weird.obj -+ctype.obj -+wcpp4stuff.obj -+i4d.bin -+i4m.bin

#
# Generic library stuff
#

!include ..\MakeCommon.mak
