# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

#
# XOSL library specific stuff
#

COMPILE_OBJ=xoslmain.obj xoslapp.obj loader.obj &
            xosldata.obj items.obj &
            encpwd.obj fatfix.obj drvswap.obj &
            antivir.obj bypass.obj strtable.obj &
            setup.obj bootkeys.obj &
            prefer.obj general.obj password.obj &
            about.obj dialogs.obj &
            lastconf.obj &
            part.obj hide.obj &
            graphset.obj colorset.obj mouseset.obj &
            xoslpass.obj misc.obj default.obj
LIB_NAME=xosl.lib
LIST_FILE=xosl.lst
LIB_OBJ=-+xoslmain.obj -+xoslapp.obj -+loader.obj &
        -+xosldata.obj -+items.obj &
        -+encpwd.obj -+fatfix.obj -+drvswap.obj &
        -+antivir.obj -+bypass.obj -+strtable.obj &
        -+setup.obj -+bootkeys.obj &
        -+prefer.obj -+general.obj -+password.obj &
        -+about.obj -+dialogs.obj &
        -+lastconf.obj &
        -+part.obj -+hide.obj &
        -+graphset.obj -+colorset.obj -+mouseset.obj &
        -+xoslpass.obj -+misc.obj -+default.obj

#
# Generic library stuff
#

!include ..\MakeCommon.mak
