# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

#
# String library specific stuff
#

COMPILE_OBJ=cstring.obj string.obj mem.obj digits.obj
LIB_NAME=string.lib
LIST_FILE=string.lst
LIB_OBJ=-+cstring.obj -+string.obj -+mem.obj +-digits.obj

#
# Generic library stuff
#

!include ..\MakeCommon.mak
