# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

CONV_OUT=ipls.bin
LBA_OUT=iplslba.bin

CONV_OBJ=starter.obj mainconv.obj transfer.obj diskconv.obj mem.obj convfill.obj
LBA_OBJ=starter.obj mainlba.obj lbatrans.obj disklba.obj mem.obj lbafill.obj
FIL_CONV_OBJ=starter.obj, mainconv.obj, transfer.obj, diskconv.obj, mem.obj, convfill.obj
FIL_LBA_OBJ=starter.obj, mainlba.obj, lbatrans.obj, disklba.obj, mem.obj, lbafill.obj

CONV_MAP=ipls.map
LBA_MAP=iplslba.map

INCPATH=.

#-zdp ?
CPP_OPTIONS=-w4 -e25 -ei -zp1 -zq -ecc -zls -os -s -zc -3 -bt=dos -fo=.obj -zdp -ms -xd -xr -v -i$(INCPATH)
ASM_OPTIONS=-zq
LINK_OPTIONS=FORMAT dos com op m op nod op maxe=25 op d op q op symf

CPP=wpp $(CPP_OPTIONS)
ASM=wasm $(ASM_OPTIONS)
LINK=wlink

all: $(CONV_OUT) $(LBA_OUT)

clean: .SYMBOLIC
   @if exist *.obj del *.obj
   @if exist *.bak del *.bak
   @if exist *.bin del *.bin
   @if exist *.map del *.map

$(CONV_OUT): .SYMBOLIC $(CONV_OBJ)
    $(LINK) name $(CONV_OUT) $(LINK_OPTIONS) FIL $(FIL_CONV_OBJ)

$(LBA_OUT): .SYMBOLIC $(LBA_OBJ)
    $(LINK) name $(LBA_OUT) $(LINK_OPTIONS) FIL $(FIL_LBA_OBJ)
		
.cpp.obj:
   $(CPP) $<

.asm.obj:
   $(ASM) $<

