# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#


#
# freemem library specific stuff
#

COMPILE_OBJ=freemem.obj

LIB_NAME=freemem.lib
LIST_FILE=freemem.lst
LIB_OBJ=-+freemem.obj

#
# Generic library stuff
#

#
# Generic library stuff
#

!include ..\MakeCommon.mak
