# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

#
# IO library specific stuff
#

COMPILE_OBJ=disk.obj fs.obj fat16.obj fat32.obj transfer.obj lbatrans.obj
LIB_NAME=io.lib
LIST_FILE=io.lst
LIB_OBJ=-+disk.obj -+fs.obj -+fat16.obj -+fat32.obj -+transfer.obj -+lbatrans.obj

#
# Generic library stuff
#

!include ..\MakeCommon.mak
