# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

#
# Misc library specific stuff
#

COMPILE_OBJ=starter.obj weird.obj ctype.obj wcpp4stuff.obj
LIB_NAME=misc.lib
LIST_FILE=misc.lst
LIB_OBJ=-+weird.obj -+ctype.obj -+wcpp4stuff.obj -+i4d.bin -+i4m.bin

#
# Generic library stuff
#

!include ..\MakeCommon.mak
