# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

#
# Keyboard library specific stuff
#

COMPILE_OBJ=keyboard.obj key.obj keys_us.obj keys_fr.obj keys_gr.obj
LIB_NAME=keyboard.lib
LIST_FILE=keyboard.lst
LIB_OBJ=-+keyboard.obj -+key.obj -+keys_us.obj -+keys_fr.obj -+keys_gr.obj

#
# Generic library stuff
#

!include ..\MakeCommon.mak
