# Open Watcom MAKEFILE
#
# Extended Operating System Loader (XOSL)
# Copyright (c) 1999 by Geurt Vos
# This code is distributed under GNU General Public License (GPL)
# The full text of the license can be found in the GPL.TXT file,
# or at http://www.gnu.org
#
# Open Watcom Migration
# Copyright (c) 2010 by Mario Looijkens:
#

#
# GUI library specific stuff
#

COMPILE_OBJ=screen.obj backgnd.obj control.obj wndlist.obj form.obj   &
            bevel.obj button.obj checkbox.obj edit.obj image.obj      &
            label.obj listbox.obj strlist.obj progress.obj scroll.obj &
            tab.obj trackbar.obj radiogrp.obj anicntrl.obj combobox.obj
LIB_NAME=gui.lib
LIST_FILE=gui.lst
LIB_OBJ=-+screen.obj -+backgnd.obj -+control.obj -+wndlist.obj -+form.obj   &
        -+bevel.obj -+button.obj -+checkbox.obj -+edit.obj -+image.obj      &
        -+label.obj -+listbox.obj -+strlist.obj -+progress.obj -+scroll.obj &
        -+tab.obj -+trackbar.obj -+radiogrp.obj -+anicntrl.obj -+combobox.obj

#
# Generic library stuff
#

!include ..\MakeCommon.mak
